# SDK1 config (INI style)
# Path to ONNX model
onnx_model_path = /home/lenovo/.config/legged/policy.onnx

# Scales
act_scale = 0.5
vel_scale = 2.0
gyr_scale = 0.25
dof_pos_scale = 1.0
dof_vel_scale = 0.05

# Clipping
obs_clip = 100.0

# History steps (>=1)
history_steps = 6

# Optional: obs_size override (default 45)
obs_size = 45

# Default joint positions, orders:
  ; FR_hip_joint, FR_thigh_joint, FR_calf_joint,
  ; FL_hip_joint, FL_thigh_joint, FL_calf_joint,
  ; RR_hip_joint, RR_thigh_joint, RR_calf_joint,
  ; RL_hip_joint, RL_thigh_joint, RL_calf_joint
dft_dof_pos = 0.0, 0.8, -1.5, 0.0, 0.8, -1.5, 0.0, 0.8, -1.5, 0.0, 0.8, -1.5

# Mapping from policy index -> robot joint index (12 ints), 0-11 to robot_order index
  ; FL_hip_joint, FL_thigh_joint, FL_calf_joint,
  ; FR_hip_joint, FR_thigh_joint, FR_calf_joint,
  ; RL_hip_joint, RL_thigh_joint, RL_calf_joint,
  ; RR_hip_joint, RR_thigh_joint, RR_calf_joint
joint_idx_rob2pol = 3, 4, 5, 0, 1, 2, 9, 10, 11, 6, 7, 8